org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
CUSTOMER_FLUTTER_APPLICATION_ID=com.siamblend
CUSTOMER_FLUTTER_APP_LABEL=SiamBlend
CUSTOMER_FLUTTER_AUTH_CALLBACK_SCHEME=siamblend
CUSTOMER_FLUTTER_AUTH_CALLBACK_HOST=siamblend.com
