services:
  customer-flutter-web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        API_BASE_URL: ${API_BASE_URL:-/api/v1}
        APP_LOCALE: ${APP_LOCALE:-th-TH}
    ports:
      - "8080:80"
