apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: newpaotang-prod
resources:
  - ../digitalocean
  - support-api.yaml
images:
  - name: newpaotang/support-api
    newName: registry.digitalocean.com/REPLACE_WITH_REGISTRY/newpaotang-support-api
    newTag: REPLACE_WITH_TAG
