apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: deepay-webhook
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/whitelist-source-range: "159.65.135.215/32"
    nginx.ingress.kubernetes.io/proxy-body-size: "1m"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.siamblend.com
      secretName: siamblend-public-tls
    - hosts:
        - api.lottery80.online
      secretName: newpaotang-public-tls
  rules:
    - host: api.siamblend.com
      http:
        paths:
          - path: /api/v1/webhooks/topups/deepay_kbank
            pathType: Exact
            backend:
              service:
                name: platform-api
                port:
                  number: 8000
    - host: api.lottery80.online
      http:
        paths:
          - path: /api/v1/webhooks/topups/deepay_kbank
            pathType: Exact
            backend:
              service:
                name: platform-api
                port:
                  number: 8000
