apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: siamblend-public-tls
spec:
  secretName: siamblend-public-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - siamblend.com
    - "*.siamblend.com"
