<?php

return [
    'api_version' => 'v1',
    'tenant_resolution' => [
        'active_partner_status' => 'active',
        'active_tenant_status' => 'active',
        'active_domain_status' => 'active',
    ],
    'audit' => [
        'sensitive_keys' => [
            'password',
            'password_confirmation',
            'token',
            'access_token',
            'refresh_token',
            'secret',
            'state',
            'challenge_token',
            'totp_secret',
            'recovery_code',
            'recovery_codes',
            'line_code',
            'hash',
            'invite',
            'invitation',
            'authorization',
            'credentials',
            'api_key',
            'webhook',
            'dsn',
            'bank',
            'bank_account',
            'account',
            'account_number',
            'promptpay',
            'iban',
            'swift',
        ],
    ],
    'realtime' => [
        'app_id' => env('REVERB_APP_ID'),
        'admin_key' => env('REVERB_APP_KEY', 'newpaotang-admin'),
        'admin_secret' => env('REVERB_APP_SECRET', env('APP_KEY') ?: 'newpaotang-admin-secret'),
        'customer_key' => env('REVERB_APP_KEY', 'newpaotang-customer'),
        'customer_secret' => env('REVERB_APP_SECRET', env('APP_KEY') ?: 'newpaotang-customer-secret'),
        'host' => env('REVERB_HOST', 'localhost'),
        'port' => env('REVERB_PORT', 8080),
        'scheme' => env('REVERB_SCHEME', 'http'),
        'auth_ttl_seconds' => 300,
    ],
    'lotto_scraper' => [
        'hmac_secret' => env('LOTTO_SCRAPER_HMAC_SECRET', 'newpaotang-local-lotto-scraper-secret'),
        'signature_ttl_seconds' => max(60, (int) env('LOTTO_SCRAPER_SIGNATURE_TTL_SECONDS', 300)),
        'trigger_url' => env('LOTTO_SCRAPER_TRIGGER_URL', 'http://lotto-scraper:3200/internal/poll'),
        'trigger_urls' => array_values(array_filter(array_map(
            static fn (string $url): string => trim($url),
            explode(',', (string) env('LOTTO_SCRAPER_TRIGGER_URLS', env('LOTTO_SCRAPER_TRIGGER_URL', 'http://lotto-scraper:3200/internal/poll'))),
        ))),
        'trigger_source_urls' => [
            'sanook' => env('LOTTO_SCRAPER_TRIGGER_SANOOK_URL'),
            'thairath' => env('LOTTO_SCRAPER_TRIGGER_THAIRATH_URL'),
        ],
        'trigger_secret' => env('LOTTO_SCRAPER_TRIGGER_SECRET', env('LOTTO_SCRAPER_HMAC_SECRET', 'newpaotang-local-lotto-scraper-secret')),
        'trigger_timeout_seconds' => max(1, (int) env('LOTTO_SCRAPER_TRIGGER_TIMEOUT_SECONDS', 15)),
    ],
    'line' => [
        'client_id' => env('LINE_LOGIN_CHANNEL_ID'),
        'client_secret' => env('LINE_LOGIN_CHANNEL_SECRET'),
        'authorize_url' => env('LINE_LOGIN_AUTHORIZE_URL', 'https://access.line.me/oauth2/v2.1/authorize'),
        'token_url' => env('LINE_LOGIN_TOKEN_URL', 'https://api.line.me/oauth2/v2.1/token'),
        'profile_url' => env('LINE_LOGIN_PROFILE_URL', 'https://api.line.me/v2/profile'),
        'callback_url' => env('LINE_LOGIN_CALLBACK_URL'),
        'state_ttl_seconds' => 600,
        'provider_exchange_enabled' => env('LINE_LOGIN_PROVIDER_EXCHANGE_ENABLED', false),
    ],
    'runtime' => [
        'worker_queues' => array_values(array_filter(array_map(
            'trim',
            explode(',', (string) env('PLATFORM_WORKER_QUEUES', 'partner-inbox-high,partner-inbox-normal,stock-allocation,stock-generation,stock-image-generation,stock-partner-image-generation,stock-sold-events,stock-recall,reservation-expiration,checkout-finalize,central-outbox,affiliate-commission,reward-validate,reward-check-high,reward-check-normal,reward-summary,reward-publish,reward-notification,report-build,webhook-dispatch,notification,usage-metering,partner-monitoring,default')),
        ))),
    ],
    'stock_generation' => [
        'queue' => env('STOCK_GENERATION_QUEUE', 'stock-generation'),
        'chunk_rounds' => max(1, (int) env('STOCK_GENERATE_CHUNK_ROUNDS', 5)),
        'image_dispatch_chunk_size' => max(1, (int) env('STOCK_GENERATE_IMAGE_DISPATCH_CHUNK_SIZE', 500)),
        'base_lottery_numbers_path' => env('BASE_LOTTERY_NUMBERS_PATH', storage_path('app/public/number.json')),
        'base_lottery_seed_chunk' => max(100, min(10000, (int) env('BASE_LOTTERY_SEED_CHUNK', 5000))),
        'seed_base_lottery_on_initial_seed' => filter_var(
            env('BASE_LOTTERY_SEED_ON_INITIAL_SEED', env('APP_ENV') !== 'testing'),
            FILTER_VALIDATE_BOOL,
        ),
    ],
    'migration_rehearsal' => [
        'source_type' => env('MIGRATION_REHEARSAL_SOURCE_TYPE', 'synthetic_seeded_only'),
        'source_dsn' => env('MIGRATION_REHEARSAL_SOURCE_DSN'),
        'source_token' => env('MIGRATION_REHEARSAL_SOURCE_TOKEN'),
        'object_storage_bucket' => env('MIGRATION_REHEARSAL_OBJECT_STORAGE_BUCKET'),
        'secret_reference' => env('MIGRATION_REHEARSAL_SECRET_REFERENCE'),
        'release_image_tag' => env('PLATFORM_RELEASE_IMAGE_TAG'),
        'previous_image_tag' => env('PLATFORM_PREVIOUS_IMAGE_TAG'),
    ],
    'observability' => [
        'enabled' => env('PLATFORM_OBSERVABILITY_ENABLED', true),
        'environment' => env('PLATFORM_OBSERVABILITY_ENV', env('APP_ENV', 'local')),
        'metrics_label' => env('PLATFORM_METRICS_LABEL', 'local'),
    ],
    'alerts' => [
        'enabled' => env('PLATFORM_ALERTS_ENABLED', true),
        'channels' => array_values(array_filter(array_map(
            'trim',
            explode(',', (string) env('PLATFORM_ALERT_CHANNELS', 'database,log')),
        ))),
        'webhook_url' => env('PLATFORM_ALERT_WEBHOOK_URL'),
        'external_delivery_enabled' => env('PLATFORM_ALERT_EXTERNAL_DELIVERY_ENABLED', false),
    ],
    'cloudflare' => [
        'account_id' => env('CLOUDFLARE_ACCOUNT_ID'),
        'zone_id' => env('CLOUDFLARE_ZONE_ID'),
        'api_token' => env('CLOUDFLARE_API_TOKEN'),
        'api_base_url' => env('CLOUDFLARE_API_BASE_URL', 'https://api.cloudflare.com/client/v4'),
        'dry_run' => env('CLOUDFLARE_DRY_RUN', true),
        'proxy_required' => env('CLOUDFLARE_PROXY_REQUIRED', true),
        'https_required' => env('CLOUDFLARE_HTTPS_REQUIRED', true),
    ],
    'ticket_images' => [
        'cdn_required' => env('TICKET_IMAGE_CDN_REQUIRED', true),
        'cdn_base_url' => env('CDN_BASE_URL'),
        'r2_endpoint' => env('R2_ENDPOINT'),
        'r2_bucket' => env('R2_BUCKET'),
        'r2_access_key_id' => env('R2_ACCESS_KEY_ID'),
        'r2_secret_access_key' => env('R2_SECRET_ACCESS_KEY'),
        'image_path' => env('TICKET_IMAGE_CDN_IMAGE_PATH', env('IMAGE_PATH')),
    ],
    'seed' => [
        'central_admin_email' => env('PLATFORM_SEED_CENTRAL_ADMIN_EMAIL', 'admin@newpaotang.test'),
        'central_admin_password' => env('PLATFORM_SEED_CENTRAL_ADMIN_PASSWORD', 'NewPaotangAdmin!2026'),
        'tenant_owner_password' => env('PLATFORM_SEED_TENANT_OWNER_PASSWORD', 'NewPaotangTenant!2026'),
    ],
];
